// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file model.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;
namespace ProjectRenton
{
    
    public sealed class modelInput
    {
        public ImageFeatureValue image_tensor; // BitmapPixelFormat: Rgba8, BitmapAlphaMode: Premultiplied, width: 320, height: 320
    }
    
    public sealed class modelOutput
    {
        public TensorFloat detected_boxes; // shape(1,-1,4)
        public TensorInt64Bit detected_classes; // shape(1,-1)
        public TensorFloat detected_scores; // shape(1,-1)
    }
    
    public sealed class modelModel
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<modelModel> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            modelModel learningModel = new modelModel();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<modelOutput> EvaluateAsync(modelInput input)
        {
            binding.Bind("image_tensor", input.image_tensor);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new modelOutput();
            output.detected_boxes = result.Outputs["detected_boxes"] as TensorFloat;
            output.detected_classes = result.Outputs["detected_classes"] as TensorInt64Bit;
            output.detected_scores = result.Outputs["detected_scores"] as TensorFloat;
            return output;
        }
    }
}

